# 使用 /ohs reload重载配置文件
# 该命令需要权限：ohs.command.reload
# 重载后，必须重新上传oraxen资源包

# 使用哪种存储 pan / tencent-cos
client: pan

# 123云盘
pan:
  base-url: https://open-api.123pan.com
  client-id:
  client-secret:
  # 保存材质包的文件夹id
  parent-file-id: 8187024

# 腾讯云对象存储
tencent-cos:
  secret-id:
  secret-key:
  # bucket的地域
  region-name:
  # bucket名
  bucket-name:
  # 下载链接有效期（分钟）
  expire-time: 30
  # 资源包在bucket的存储路径
  key: bili_oraxen_pack/pack.zip