name: ResourcePackHostingService
version: '${project.version}'
author: BigBrother
main: com.bigbrother.resourcepackhostingservice.ResourcePackHostingService
api-version: '1.20'
depend: [Oraxen]
commands:
  basecommand:
    description: 插件基础指令
    usage: 使用 /rphs reload 重载配置文件；/rphs packurl 获取资源包的URL
    aliases: [ rphs ]
    permission: rphs.command.reload
libraries:
  - com.qcloud:cos_api:5.6.229
  - software.amazon.awssdk:s3:2.26.21
